[build]
  command = """
    npm install --legacy-peer-deps
    npm run build
  """
  publish = "dist/coreui-free-angular-admin-template/browser"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
