[build]
  command = "npm install && npm install -g @angular/cli && npm run build"
  publish = "dist/coreui-free-angular-admin-template/browser"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
